# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_id', models.CharField(max_length=150, unique=True)),
                ('content', models.TextField(default=' ', null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('key_words', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '商品评论',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=50)),
                ('category', models.TextField(default=' ', null=True)),
                ('detail', models.TextField(default=' ', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.Goods'),
        ),
    ]
